apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitpath
resources:
  - ../../base
images:
  - name: ghcr.io/renzoal7/gitpath
    newName: ghcr.io/renzoal7/gitpath
    newTag: sha-9335add0bd2292fd125469a8042824aba4df40cc
