apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitpath
resources:
  - ../../base
images:
  - name: ghcr.io/renzoal7/gitpath
    newName: ghcr.io/renzoal7/gitpath
    newTag: sha-febb457e6083d5312cb086e91ce2af813ba344fd
