apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitpath
resources:
  - ../../base
images:
  - name: ghcr.io/renzoal7/gitpath
    newName: ghcr.io/renzoal7/gitpath
    newTag: sha-c7160aab9763f547fdd09b72099ed795f50a9dfc
