apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitpath-prod
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: gitpath
    app.kubernetes.io/managed-by: cortex-root
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/RenzoAL7/K3s-Cortex.git
    targetRevision: main
    path: apps/gitpath/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: gitpath
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
