apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gitpath
  labels:
    app.kubernetes.io/name: gitpath
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gitpath
